Logs
| project TimeGenerated,UserPrincipalName, CA, DeviceDetail, IPAddress, NetworkLocationDetails, AppDisplayName, ResourceDisplayName, ResultType, ResultDescription
| summarize  UsersCNT = dcount(UserPrincipalName), FailureUsers = make_set_if(UserPrincipalName, tostring(CA.["[ZERO TRUST] Apps available only from trusted devices"]) == "failure") by Result = tostring(CA.["[ZERO TRUST] Apps available only from trusted devices"]), bin(TimeGenerated, 15m)
//| summarize  UsersCNT = count() by Result = tostring(CA.["[ZERO TRUST] Apps available only from trusted devices"]), bin(TimeGenerated, 15m)
| sort by Result asc, TimeGenerated asc
| extend Accumulated=row_cumsum(UsersCNT, Result != prev(Result))
| project-away  UsersCNT
| render timechart
